project:
  type: website

website:
  page-footer: 
      center: "Built in R with Quarto" 
  title: "Jack Huber"
  navbar:
    right:
      - href: projects.qmd
        text: "Projects"
      - href: presentations.qmd
        text: "Presentations"
      - href: pubs.qmd
        text: "Writing"
      - href: teaching.qmd
        text: "Teaching"
      - href: CV.qmd
        text: "CV"
      - href: JBH_Resume.pdf
        text: "Resume"
    background: navy
    foreground: light
    

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false

editor: visual

