project:
  type: website

website:
  page-footer: 
      center: "Built in R with Quarto" 
  title: "Jack Huber"
  navbar:
    right:
      - href: index.qmd
        text: "Home"
      - href: presentations.qmd
        text: "Presentations"
      - href: projects.qmd
        text: "Projects"
      #- href: JBH_Resume.pdf
      #  text: Resume
      - href: teaching.qmd
        text: "Teaching"
      - href: pubs.qmd
        text: "Writing"
    background: navy
    foreground: light

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false

editor: visual

