---
title: "Current projects"
editor: visual
---

## Health Care

[Outcomes of Monoclonal Antibody Use in Patients with COVID-19](http://mabs.jackhuber.org) - a propensity-matched comparison of the effect of monoclonal antibodies on 28-day rehospitalization and mortality in 21,139 outpatients with mild-to-moderate COVID-19 infections who presented to Swedish Medical Center emergency departments from 2021 to 2022

[Predicting Mortality in Patients with Necrotizing Fasciitis: A Machine Learning Study](http://necrotizingfasciitis.jackhuber.org) - Unsupervised and supervised models to predict mortality in 158 patients diagnosed with necrotizing fasciitis (flesh-eating bacterial infections) at Beth Israel Deaconess Medical Center in Boston from 2008 to 2019

[Predicting Mortality in Heart Failure Patients Admitted to ICU](http://mortality.jackhuber.org) - a logistic regression analysis of mortality in 1,177 adult heart failure (HF) patients admitted to Beth Israel Deaconess Medical Center in Boston from 2008 to 2019

## Religion

### Tableau visualizations

[Retention, Transition, and Disaffiliation from American Christianity: Trend Data from the General Social Survey, 1972-2018](https://public.tableau.com/views/RetentionTransitionandDisaffilationinAmericanChristianity/Title?:language=en-US&:sid=&:redirect=auth&:display_count=n&:origin=viz_share_link) - A nifty tool for exploring trends of retention and transition in American religious affiliation as well as a specific focus on disaffiliation from Christianity, based on data are from the General Social Survey, 1973 to 2018.

[America's Changing Religious Traditions](https://public.tableau.com/views/AmericasChangingReligiousTraditions/AdultTraditions?:language=en-US&:sid=&:redirect=auth&:display_count=n&:origin=viz_share_link) - A Sankey diagram visualization of data from the Pew Research Center's 2015 "Changing Religious Landscape" study

### In-progress

Validity Evidence for the Spiritual Harm and Abuse Scale (SHAS) - [Koch and Edstrom (2022)](https://doi.org/10.1111/jssr.12792) developed a scale of spiritual harm and abuse by religious leaders. Here I plan to use the Rating Scale Model to examine the technical quality of the scale for use in research.
<!-- [Validity Evidence for the Spiritual Harm and Abuse Scale (SHAS)](https://spiritual-abuse.jackhuber.org) -->

Validity of a Scale of Spiritual Well-Being - The Pew Research Center 2015 Changing Religious Landscape survey included four items that could form a scale of spiritual well-being. I plan to use classical test theory and item response theory to assess the technical quality of this scale for use in research.
<!-- [Validity of a Scale of Spiritual Well-Being](http://spiritual-well-being.jackhuber.org) -->

Coping during the COVID-19 Pandemic
<!-- [Prayer as Spiritual Coping during the COVID-19 Pandemic](https://covid-prayer.jackhuber.org/) -->

A Closer Look at Glossolalia
<!-- [A Closer Look at Glossolalia](https://tongues.jackhuber.org/) -->
