---
title: "Writing"
editor: visual
---

------------------------------------------------------------------------

Huber, J., Schnitzer, D., Barry, H., Scanlan, J. Outcomes of Monoclonal Antibodies in Patients with COVID-19. JMIR Preprints 03/05/2024:60175 DOI: [10.2196/preprints.60175](https://preprints.jmir.org/preprint/60175)

Monpas-Huber, J.B. (2015). [Just pressing buttons? Validity evidence for the STAR and Smarter Balanced Summative Assessments](https://github.com/jackbhuber/pubs/blob/30a19d1c6553af42d57a8cca55fd88aa97984f3a/2015_JustPressingButtons_WERAJournal_1115.pdf). *The WERA Educational Journal*, 8(1), pp. 39-44. Washington Educational Research Association (WERA)

Monpas-Huber, J.B. (2013). Assessing teacher effectiveness: Charlotte Danielson's presentation at the December 2012 WERA Conference. *The Standard Deviation Newsletter*, pp. 12-13. Washington Educational Research Association (WERA)

Monpas-Huber, J.B. (2011). [Validity of college and career readiness assessments](https://github.com/jackbhuber/pubs/blob/081e10c1aa40990035690b9fccd72482c25c35a6/2011_ValidityofCollegeCareer_WERAJournal_1211.pdf). *The WERA Educational Journal*, 4(1), pp. 10-12. Washington Educational Research Association (WERA)

Monpas-Huber, J.B. (2010). [Explaining high school teachers instructional use of state assessment data: A multilevel study from Washington State](https://journals.sagepub.com/doi/10.1177/105268461002000205). *Journal of School Leadership*, 20(2), pp. 208-237.

Monpas-Huber, J.B. (2009). [Aligning district and state assessments to measure growth in achievement](https://github.com/jackbhuber/pubs/blob/46933673d8913fe3b37a20ac0ce31f736bbff979/2009_AligningDistrictStateAssessments_WERAJournal_0209.pdf). *The Standard Deviation Newsletter and Educational Journal*, 1(1), pp. 47-50. Washington Educational Research Association (WERA)

De Leeuw, H., & Monpas-Huber, J.B. (2009). Achievement of English Language Learners. *Leadership Information*, 7(3), pp. 1-23. School Information and Research Service, Washington Association of School Administrators (WASA)

Monpas-Huber, J.B. (2008). [Validity issues for common district assessments](https://github.com/jackbhuber/pubs/blob/441fb8e91680a21075cacd6c2c1b212779b5a375/2008_ValidityForCommonDistrictAssesments_StdDev_0108.pdf). *The Standard Deviation Newsletter*, pp. 20-29. Washington Educational Research Association (WERA)

Knapp, M.S., Swinnerton, J.A., Copland, M.A., & Monpas-Huber, J.B. (2006). [Data-informed leadership in education](https://www.education.uw.edu/ctp/sites/default/files/ctpmail/PDFs/DataInformed-Nov1.pdf). Seattle, WA: Center for the Study of Teaching and Policy, University of Washington

<!-- ## Doctoral dissertation -->

<!-- **Monpas-Huber, J.B.** (2007). [Context and motivation to use state assessment data: A multilevel study of high school teachers in Washington State](https://orbiscascade-washington.primo.exlibrisgroup.com/permalink/01ALLIANCE_UW/1juclfo/alma99122253190001452). Department of Educational Psychology, College of Education, University of Washington, Seattle, WA -->

<!-- ## Master thesis -->

<!-- **Monpas-Huber, J.B.** (1997). [Structure and ideology in the mobilization of the New Christian Right: A test of a model](https://vtechworks.lib.vt.edu/handle/10919/41008). Department of Sociology, Virginia Polytechnic Institute & State University, Blacksburg, VA -->
