---
title: "Talks"
editor: visual
---

------------------------------------------------------------------------

Huber, J.B. (2023). [Tips and tools for statistical data analysis](https://github.com/jackbhuber/talks/blob/7c78b6905cefb064e695db1c0ece1478e2f19238/2023_TipsandTools_SwedishLearningDay_103123.pdf). Presented at Swedish Learning & Celebration Day. Swedish Medical Center Cherry Hill Campus, Seattle, WA

Huber, J.B. (2018). [Bias in standardized testing](https://github.com/jackbhuber/talks/blob/9512d57d71405795fd703bb6844c7dd73e4968f0/2018_BiasInStandardizedTesting_WERA_120618.pdf). Presented at the Washington Educational Research Association (WERA) / Office of the Superintendent of Public Instruction (OSPI) State Assessment Conference, SeaTac, WA

Huber, J.B. (2018). [A closer look at summer change: Lessons from longitudinal data](https://github.com/jackbhuber/talks/blob/d03db8d2bd987d0b9ca05a0f5923347904a20a76/2018_ACloserLookAtSummerChange_Fusion_0618.pdf). Summer Fusion Conference of Northwest Evaluation Association (NWEA), Portland, OR

Monpas-Huber, J.B. (2015). [The relationship between Fountas & Pinnell Benchmark Assessment System and Smarter Balanced English and Language Arts Assessments, Grades 3-5](https://github.com/jackbhuber/talks/blob/bec125e98f93ee3e8e32f7f21ebe420bf97e8e80/2015_FB-SBA-Correlations_WERAPreconference_1215.pdf). Presented at the Washington Educational Research Association (WERA) / Office of the Superintendent of Public Instruction (OSPI) State Assessment Conference, SeaTac, WA

Monpas-Huber, J.B. (2015). [Just pressing buttons? Validity evidence for the STAR Assessments and Smarter Balanced Summative Assessments](https://github.com/jackbhuber/talks/blob/62ac1713b3f545576918ef33d045f11f6c03b392/2015_ValidityEvidenceforSTARSBAAssessment_WSSDAConference_112015.pdf). Presented at the Washington State School Directors Association (WSSDA) Conference, Bellevue, WA

Monpas-Huber, J.B., & Garrett, M. (2012). [The course challenge test: A catalyst for change?](https://github.com/jackbhuber/talks/blob/e29d26d1897bea6b8e85a731fa404f2f6baf9dac/2012_TheCourseChallengeTest_WERA_1212.pdf) Presented at the Washington Educational Research Association (WERA) / Office of the Superintendent of Public Instruction (OSPI) State Assessment Conference, SeaTac, WA

Monpas-Huber, J.B. (2012). [Growth inferences from district and state assessments: A look at elementary reading](https://github.com/jackbhuber/talks/blob/fc79815b144a95ac781ac74fc4e42a126c07aad5/2012_GrowthInferencesFromDistrictStateAssessments_WERA_032912.pdf). Presented at the Washington Educational Research Association (WERA) / Office of the Superintendent of Public Instruction (OSPI) State Assessment Conference, SeaTac, WA

Monpas-Huber, K., & Monpas-Huber, J.B. (2011). [The role of reading strategies in middle school reading comprehension: A classroom-based action research project](https://github.com/jackbhuber/talks/blob/63f14dba2745facb110eadd9864dc46183a78dac/2011_ReadingStrategies_WERA_1211.pdf). Presented at the Washington Educational Research Association (WERA) / Office of the Superintendent of Public Instruction (OSPI) State Assessment Conference, SeaTac, WA

Alonzo, J., Monpas-Huber, J.B., & Henry, S. (2010). Increasing student achievement with response to intervention and curriculum-based measurement. Presented at the Washington Educational Research Association (WERA) / Office of the Superintendent of Public Instruction (OSPI) State Assessment Conference, SeaTac, WA

Cummings, P., Monpas-Huber, J.B., & Wakeley, D. (2009). [Tricks of the trade: Validity of standards-based grades](https://github.com/jackbhuber/talks/blob/7267589f0c2a24a6c38329cf25dcec707cd7c0c5/2009_ValidityofStdsBasedGrades_WERA_1209.pdf). Presented at the Washington Educational Research Association (WERA) / Office of the Superintendent of Public Instruction (OSPI) State Assessment Conference, SeaTac, WA

Monpas-Huber, J.B., & Henry, S. (2009). [Using data from common district assessments to inform decisions about middle school mathematics: Lessons from Shoreline Public Schools](https://github.com/jackbhuber/talks/blob/8faba1d70054c5536da9b4a3944a37688d5749ad/2009_JBMH%26Henry_Common%20Assessments_WERA_1209.pdf). Presented at the Washington Educational Research Association (WERA) / Office of the Superintendent of Public Instruction (OSPI) State Assessment Conference, SeaTac, WA

Monpas-Huber, J.B., & Cummings, P. (2009). The how and why of podcasting for assessment folks. Presented at the Washington Educational Research Association (WERA) / Office of the Superintendent of Public Instruction (OSPI) State Assessment Conference, SeaTac, WA

Monpas-Huber, J.B., & Gering, S. (2009). [Building a data dashboard: The role of research](https://github.com/jackbhuber/talks/blob/33f09160d92ba8e0b95636f9b9f241f7c17b160c/2009_BuildingADataDashboard_WERA_0309.pdf). Presented at the March Meeting of the Washington Educational Research Association (WERA), SeaTac, WA

Monpas-Huber, J. B. (2008). [Aligning assessments to monitor growth in mathematics achievement: A validity study](https://github.com/jackbhuber/talks/blob/3b875e34bf6ebdf4c728c5869d45e086eb29548b/2008_AligningAssessments_WERA_1208.pdf). Presented at the December Meeting of the Washington Educational Research Association (WERA), SeaTac, WA

Monpas-Huber, J.B. (2008). High school teachers' use of data: A multilevel study. Presented at the Annual Meeting of the American Educational Research Association (WERA), New York, NY

De Leeuw, H. & Monpas-Huber, J.B. (2007). WASL performance of exited English language learners: Interesting findings and possible explanations. Presented at December Meeting of the Washington Educational Research Association (WERA), SeaTac, WA

Oakley, D., Lindeblad, K., Rye, G., Dennis, K., & Monpas-Huber, J.B. (2007). Using district assessments to improve mathematics instruction: The experience of Spokane Public Schools. Presented at the December Meeting of the Washington Educational Research Association (WERA), SeaTac, WA

Monpas-Huber, J.B. (2007). Validity issues for medium-scale district assessments. Presented at the December Meeting of the Washington Educational Research Association (WERA), SeaTac, WA

De Leeuw, H. & Monpas-Huber, J.B. (2007). Exited English language learners outperforming the district on state assessment: How can this be? Presented at the April Meeting of the Washington Association of Bilingual Education (WABE), Toppenish, WA

Monpas-Huber, J.B. (2007). Making sense of assessment data: A case study of high school leaders. Presented at the Annual Meeting of the American Educational Research Association (AERA), Chicago, IL

Monpas-Huber, J.B. (2006). High school teachers instructional use of state assessment data: Exploring the role of school culture and motivation. Presented at the December Meeting of the Washington Educational Research Association (WERA), SeaTac, WA

Silverman, R., Elman, L., & Monpas-Huber, J.B. (2005). Alternative views of state assessment (WASL) data. Presented at the December Meeting of the Washington Educational Research Association (WERA), SeaTac, WA

Monpas-Huber, J.B. (2002). The impact of school grade configuration on state assessment (WASL) performance. Presented at the December Meeting of the Washington Educational Research Association (WERA), SeaTac, WA
