---
title: "Teaching"
editor: visual
---

------------------------------------------------------------------------

## Education

[**Data Analysis for Problems of Practice**](https://EDLD710.jackhuber.org), Fall 2023, Department of Educational Leadership & Administration, School of Education, Gonzaga University, Spokane, WA

[**Methods and Instruments for Data Collection**](https://edld704.jackhuber.org), Spring 2023, Department of Educational Leadership & Administration, School of Education, Gonzaga University, Spokane, WA

**Data Analysis for Problems of Practice**, Fall 2022, Department of Educational Leadership & Administration, School of Education, Gonzaga University, Spokane, WA

**Evidence-Based Contribution to Problems of Practice**, Fall 2022, Department of Educational Leadership & Administration, School of Education, Gonzaga University, Spokane, WA

**Action Plan for Problems of Practice**, Spring 2022, Department of Educational Leadership & Administration, School of Education, Gonzaga University, Spokane, WA

**Research Methods in Education**, Winter 2007, College of Education, Washington State University-Spokane, Spokane, WA

## Sociology

**Criminology**, Fall 1999 - Spring 2000, Department of Sociology, University of Connecticut, Storrs, CT

**Social Problems**, Fall 1999 - Spring 2000, Department of Sociology, University of Connecticut, Storrs, CT
